Adding first draft of new module
cloudposse/terraform-aws-athena pull request #1
Opened 2022-07-25 17:56 UTC by danjbh

## what & why?
* New public module for deploying Amazon Athena to AWS

2022-07-25 18:03 UTC, danjbh commented
/test all

2022-07-25 18:07 UTC, danjbh commented
/test bats

2022-07-25 18:21 UTC, danjbh commented
/test terratest

2022-07-25 19:02 UTC, danjbh commented
/test terratest

2022-07-25 19:34 UTC, danjbh commented
/test all

2022-07-25 21:33 UTC, danjbh commented
/test all

2022-07-25 21:54 UTC, danjbh commented
/test all

2022-07-26 21:02 UTC, danjbh commented
Looks like I'm missing support for the data catalog in this module.. I'll get it added ASAP and will reopen this for review.

2022-07-27 20:15 UTC, danjbh commented
/test all

2022-07-28 13:09 UTC, korenyoni requested changes
Couple minor changes requested, LGTM otherwise

2022-07-28 13:09 UTC, korenyoni commented on main.tf
> +  description             = "Athena KMS Key"
```suggestion
  description             = "Athena KMS Key for ${module.this.id}"
```

2022-07-28 13:09 UTC, korenyoni commented on main.tf
> +}
Missing tags

```suggestion
  tags = module.this.tags
}
```

2022-07-29 12:54 UTC, korenyoni approved these changes
LGTM

2022-08-03 22:54 UTC, merged